<!doctype html><html><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><meta name=theme-color content="#F5F7F9"><title>Supervisor 切换用户所引起的一个 Bug. | B-log</title><link rel=stylesheet href=/css/minimalism.css><script type=application/javascript>var doNotTrack=false;if(!doNotTrack){window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;ga('create','UA-67524885-1','auto');ga('send','pageview');}</script><script async src=https://www.google-analytics.com/analytics.js></script></head><body><header><div class=container><h1><a href=/>B-log</a></h1><nav><ul><li>&nbsp;|&nbsp;</li><li><a href=/post/>Post</a></li><li>&nbsp;|&nbsp;</li><li><a href=/about/>About</a></li><li>&nbsp;|&nbsp;</li></ul></nav></div><hr></header><main><article class=post><header><h1>Supervisor 切换用户所引起的一个 Bug.</h1><ul class=description><li><time>2016-01-26</time></li><li>&nbsp;|</li><li>&nbsp;#Python</li><li>&nbsp;#supervisor</li></ul></header><section class=license><p><a rel=license href=http://creativecommons.org/licenses/by-nc-sa/4.0/><img alt="Creative Commons License" src=https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png></a><br>This work is licensed under a <a rel=license href=http://creativecommons.org/licenses/by-nc-sa/4.0/>Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.</p></section><section class=post><p>前两天在服务器上修改 supervisor 配置时遇到了一个很奇怪的 Bug,
在这里将解决过程记录下来, 以作备忘.</p><h1 id=1-问题产生>1. 问题产生</h1><p>业务的部署方式是使用 gunicorn 做 wsgi 容器, 并托管在 supervisor 中执行.
在之前为图方便, <strong>supervisor 和 gunicorn 都是以 root 权限执行的</strong>.
现在为了安全起见, 需要将 gunicorn 的执行权限改为普通用户, 在这里用户名以 cissoid
代替. 具体的操作如下:</p><ol><li>切换代码及日志目录的所有者</li></ol><div class=highlight><pre style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-Text data-lang=Text>chown -R cissoid:cissoid path/to/project
chown -R cissoid:cissoid path/to/log
</code></pre></div><ol start=2><li>修改 supervisord.conf, 将 <code>user=root</code> 修改为 <code>user=cissoid</code>, 并在 supervisor 中重启进程.</li></ol><p>结果在执行第二步时, 发现进程无法启动, 改回 user 参数后又能正常启动.</p><h1 id=2-错误排查>2. 错误排查</h1><p>在 supervisor 中提示 <code>ERROR (abnormal termination)</code>, 查看 supervisor 日志, 发现有如下日志:</p><div class=highlight><pre style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-Text data-lang=Text>2016-01-25 21:10:42,206 INFO spawned: &#39;test_server&#39; with pid 27726
2016-01-25 21:10:42,765 INFO exited: test_server (exit status 3; not expected)
2016-01-25 21:10:43,773 INFO spawned: &#39;test_server&#39; with pid 27732
2016-01-25 21:10:44,270 INFO exited: test_server (exit status 3; not expected)
2016-01-25 21:10:46,278 INFO spawned: &#39;test_server&#39; with pid 27738
2016-01-25 21:10:46,771 INFO exited: test_server (exit status 3; not expected)
2016-01-25 21:10:49,781 INFO spawned: &#39;test_server&#39; with pid 27745
2016-01-25 21:10:50,264 INFO exited: test_server (exit status 3; not expected)
2016-01-25 21:10:51,266 INFO gave up: test_server entered FATAL state, too many start retries too quickly
</code></pre></div><p>可以看出 supervisor 多次尝试重启进程均失败, 初步推断为 gunicorn 因为权限问题导致
import 失败. 打开 gunicorn 的 debug 日志, 得到如下错误日志:</p><div class=highlight><pre style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-Text data-lang=Text>2016-01-25 21:26:22 [11299] [INFO] Starting gunicorn 19.1.0
2016-01-25 21:26:22 [11299] [DEBUG] Arbiter booted
2016-01-25 21:26:22 [11299] [INFO] Listening at: http://0.0.0.0:8080 (27886)
2016-01-25 21:26:22 [11299] [INFO] Using worker: gevent
2016-01-25 21:26:22 [11304] [INFO] Booting worker with pid: 27887
2016-01-25 21:26:22 [11299] [INFO] 1 workers
2016-01-25 21:26:23 [11299] [INFO] Shutting down: Master
2016-01-25 21:26:23 [11299] [INFO] Reason: Worker failed to boot.
</code></pre></div><p>可以看到 gunicorn 并没有记录任何异常! Worker 在创建后马上就退出了. 此时判断问题可能出在
gevent 上, 于是用同样的参数手动执行 gunicorn, 结果代码正常地运行起来了&mldr;&mldr;</p><p>由于是使用同样的用户运行的代码, 能正常跑起来, 应该就可以排除权限的问题, 剩下最大的可能性是环境变量的问题.
因此在代码中增加打印 os.environ 环境变量的语句后, 再次执行, 这次果然发现了问题:
我是以 cissoid 用户在运行, 但是 HOME 的值是 /root/, USER 的值是 root, 也就是说运行时使用的是
root 用户的环境变量. 于是我去查了下 supervisor 的文档, 发现果然如此:</p><blockquote><p>The user will be changed using setuid only. This does not start a login shell
and does not change environment variables like USER or HOME.
(<a href=http://supervisord.org/configuration.html>http://supervisord.org/configuration.html</a>)</p></blockquote><p>出错的原因找到了, 确实是因为环境变量引起的,
那么环境变量不同为什么会造成这种现象呢? 继续在代码里增加一个全局的 try-catch,
发现在 import MySQLdb 时抛了异常:</p><div class=highlight><pre style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-Text data-lang=Text>ExtractionError: Can&#39;t extract file(s) to egg cache

The following error occurred while trying to extract file(s) to the Python egg cache:

  [Errno 13] Permission denied: &#39;/root/.python-eggs&#39;

The Python egg cache directory is currently set to:

  /root/.python-eggs

Perhaps your account does not have write access to this directory?  You can change the cache directory by setting the PYTHON_EGG_CACHE environment variable to point to an accessible directory.
</code></pre></div><p>原因已经说得很明显了&mldr;</p><h1 id=3-结论>3. 结论</h1><p>Python eggs 安装时会有一些 zip 压缩包, 这些压缩包在使用时会被解压到一个本地缓存目录,
这个目录在默认的情况下是 ~/.python-eggs, 因此环境变量没有改变, 使得在 supervisor
中切换用户后, 使用的缓存目录仍然是 /root/.python-eggs, 普通用户当然是没有这个目录的访问权限的.</p><p>不过很奇怪的地方在于, 异常没有在 gunicorn 中记录, 这个原因就需要有空再继续追查下去了.</p></section></article></main><footer><hr><div class=container><div class=copyright>&copy;2017-2019 By cissoid.</div><div class=about>Built with <a href=https://gohugo.io>Hugo</a>, using theme <a href=https://github.com/cissoid/hugo-theme-minimalism>Minimalism</a>.</div></div></footer><div id=mask><div id=loading><div></div></div></div><script src=/js/minimalism.js></script></body></html>